name: List Directory Contents

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List directory contents
      run: ls -al
